language: php
php:
  - 5.3

sudo: required

before_install:
  - mysql -e "create database IF NOT EXISTS lovd3_testing;" -u root
  - mysql -e "CREATE USER 'lovd'@'localhost' IDENTIFIED BY 'lovdpw'";
  - mysql -e "GRANT ALL PRIVILEGES ON 'lovd3_testing' TO 'lovd'@'localhost'";

before_script:
  - ./trunk/tests/travis/setup/before_script.sh
  - ./trunk/tests/travis/setup/setup_apache.sh
  - ./trunk/tests/travis/setup/setup_selenium_server.sh

script:
  - phpunit --verbose --debug ./trunk/tests/travis/tests/
  - phpunit --verbose --debug ./trunk/tests/phpunit_selenium/tempTest.php

notifications:
  email:
    - d.asscheman@lumc.nl