language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-intl php5-gd php5-idn php-pear php5-imagick php5-imap php5-mcrypt php5-memcache php5-ming php5-ps php5-pspell php5-recode php5-snmp php5-sqlite php5-tidy php5-xmlrpc php5-xsl xvfb

before_script:
  - ./trunk/tests/bash_scripts/setup_selenium_server.sh
  - ./trunk/tests/bash_scripts/start_selenium_server.sh

script: phpunit --verbose --log-junit ./trunk/tests/test_results/reports/testlog.xml ./tests/phpunit_selenium

notifications:
  email:
    - d.asscheman@lumc.nl