language: php
php:
##  - 5.3
##  - 5.4
  - 5.5
##  - 5.6
##  - hhvm

##matrix:
##    allow_failures:
##        - php: hhvm

sudo: required
before_script:
  - ./trunk/tests/bash_scripts/setup_apache.sh
  - ./trunk/tests/bash_scripts/setup_selenium_server.sh
  - ./trunk/tests/bash_scripts/start_selenium_sever.sh
script: "vendor/bin/phpunit --verbose --debug ./trunk/tests/phpunit_selenium/tempTest.php"