language: php
php:
#  - 5.3.3
  # aliased to 5.3.29
#  - 5.3
  # aliased to a recent 5.4.x version
#  - 5.4
  # aliased to a recent 5.5.x version
  - 5.5
  # aliased to a recent 5.6.xversion  
#  - 5.6
  # aliased to a recent 7.x version
#  - 7.0
#  - hhvm
#  - nightly

sudo: required

before_install:
  - mysql -e "create database IF NOT EXISTS lovd3_development;" -u root
  - mysql -e "CREATE USER 'lovd'@'localhost' IDENTIFIED BY 'lovd_pw';" -u root
  - mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'lovd'@'localhost';" -u root
  - mysql -e "FLUSH PRIVILEGES;"

before_script:
  - ./trunk/tests/travis/setup/before_script.sh
  - ./trunk/tests/travis/setup/setup_apache.sh
  ## IMPORTANT! convert must be run AFTER the setup_apache.sh
  ## setup_apache.sh fix some assumptions where the files are stored!
  - ./trunk/tests/bash_scripts/convert_selenium_to_phpunit.sh --localhost=trunk --continueall
  - ./trunk/tests/travis/setup/setup_selenium_server.sh

script:
  - phpunit --verbose --debug --coverage-text ./trunk/tests/travis/tests/
  - phpunit --debug --coverage-text ./trunk/tests/phpunit_selenium/adminTest.php
  - phpunit --debug --coverage-text ./trunk/tests/phpunit_selenium/collaboratorTest.php
  - phpunit --debug --coverage-text ./trunk/tests/phpunit_selenium/curatorTest.php
  - phpunit --debug --coverage-text ./trunk/tests/phpunit_selenium/importTest.php
  - phpunit --debug --coverage-text ./trunk/tests/phpunit_selenium/managerTest.php
  - phpunit --debug --coverage-text ./trunk/tests/phpunit_selenium/submitterTest.php
  - phpunit --debug --coverage-text ./trunk/tests/phpunit_selenium/tempTest.php
## Run all tests
##- phpunit --debug --coverage-text ./trunk/tests/phpunit_selenium/

notifications:
  email:
    - d.asscheman@lumc.nl