language: php
php:
##  - 5.3
##  - 5.4
##  - 5.5
  - 5.6
##  - hhvm

##matrix:
##    allow_failures:
##        - php: hhvm

sudo: required
before_script:
  - ./trunk/tests/travis/before_script.sh
##  - ./trunk/tests/bash_scripts/convert_selenium_to_phpunit.sh
script: "vendor/bin/phpunit --verbose --debug ./trunk/tests/phpunit_selenium/tempTest.php"
##script: "vendor/bin/phpunit --verbose --log-junit ./trunk/tests/test_results/reports/testlog_temp.xml ./trunk/tests/phpunit_selenium/tempTest.php"