language: php
php:
  - 5.3

sudo: required

before_install:
  - mysql -e "create database IF NOT EXISTS lovd3_development;" -u root
  - mysql -e "CREATE USER 'lovd'@'localhost' IDENTIFIED BY 'lovd_pw';" -u root
  - mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'lovd'@'localhost';" -u root
  - mysql -e "FLUSH PRIVILEGES;"

before_script:
  - ./trunk/tests/travis/setup/before_script.sh
  - ./trunk/tests/travis/setup/setup_apache.sh
  - ./trunk/tests/travis/setup/setup_selenium_server.sh

script:
  - phpunit --verbose --debug ./trunk/tests/travis/tests/
  - phpunit --verbose --debug ./trunk/tests/phpunit_selenium/tempTest.php

notifications:
  email:
    - d.asscheman@lumc.nl