## This is for LOVD3_development

language: php
php:
#  - 5.3.3
  # aliased to 5.3.29
#  - 5.3
  # aliased to a recent 5.4.x version
#  - 5.4
  # aliased to a recent 5.5.x version
#  - 5.5
  # aliased to a recent 5.6.xversion  
  - 5.6
  # aliased to a recent 7.x version
#  - 7.0
#  - hhvm
#  - nightly

sudo: required
addons:
  apt:
    packages:
      - apache2 
      - libapache2-mod-php5 
      - php5-curl 
      - php5-intl 
      - php5-gd 
      - php5-idn 
      - php-pear 
      - php5-imagick 
      - php5-imap 
      - php5-mcrypt 
      - php5-memcache 
      - php5-ming 
      - php5-ps 
      - php5-pspell 
      - php5-recode 
      - php5-snmp 
      - php5-sqlite 
      - php5-tidy 
      - php5-xmlrpc 
      - php5-xsl 
      - php5-mysql
      - phpunit-selenium


before_install:
#  - curl -s -o /home/.phpenv/versions/5.5/bin/phpunit https://phar.phpunit.de/phpunit-old.phar
#  - chmod +x /home/.phpenv/versions/5.5/bin/phpunit
  - ./trunk/tests/travis/setup/setup_mysql.sh

before_script:
  - ./trunk/tests/travis/setup/setup_apache.sh --githubaccount=dasscheman
  ## IMPORTANT! convert must be run AFTER the setup_apache.sh
  ## setup_apache.sh fix some assumptions where the files are stored!
  - ./trunk/tests/bash_scripts/convert_selenium_to_phpunit.sh --localhost=LOVD3_development --continueall
  - ./trunk/tests/travis/setup/setup_selenium_server.sh
  ##- dpkg -l phpunit-selenium

script:
  - phpunit ./trunk/tests/phpunit_selenium/adminTest.php
  - phpunit ./trunk/tests/phpunit_selenium/authorizationTest.php
  - phpunit ./trunk/tests/phpunit_selenium/collaboratorTest.php
  - phpunit ./trunk/tests/phpunit_selenium/importTest.php
  - phpunit ./trunk/tests/phpunit_selenium/managerTest.php
  - phpunit ./trunk/tests/phpunit_selenium/submitterTest.php
  - phpunit ./trunk/tests/phpunit_selenium/tempTest.php
  
## Run all tests
##  - phpunit ./trunk/tests/phpunit_selenium/

notifications:
  email:
    - d.asscheman@lumc.nl
