language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

before_install:
  - sudo apt-get update -qq
  - ./trunk/tests/bash_scripts/setup_apache.sh

before_script:
  - ./trunk/tests/bash_scripts/setup_selenium_server.sh
  - ./trunk/tests/bash_scripts/start_selenium_server.sh

script: phpunit --verbose --log-junit ./trunk/tests/test_results/reports/testlog.xml ./tests/phpunit_selenium

notifications:
  email:
    - d.asscheman@lumc.nl