language: php
php:
  - 5.3

##sudo: required
before_script:
  - ./trunk/tests/travis/setup/before_script.sh
  - ./trunk/tests/travis/setup/setup_apache.sh
  - ./trunk/tests/travis/setup/setup_selenium_server.sh

script: phpunit --verbose -c tests/phpunit.xml
##notifications:
##  email:
##    - maxtobiasweber@gmail.com

##  - ./trunk/tests/bash_scripts/setup_apache.sh
##  - ./trunk/tests/bash_scripts/setup_selenium_server.sh
##  - ./trunk/tests/bash_scripts/start_selenium_sever.sh
##script: "vendor/bin/phpunit --verbose --debug ./trunk/tests/phpunit_selenium/tempTest.php"