language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

before_script:
  - chmod +x trunk/tests/setup/bash_scripts/setup_travis.sh
  - ./trunk/tests/setup/bash_scripts/setup_travis.sh

script: phpunit --verbose --log-junit ./trunk/tests/test_results/reports/testlog.xml ./tests/phpunit_selenium

notifications:
  email:
    - d.asscheman@lumc.nl