language: php
php:
  - 5.3

sudo: required
before_script:
  - ./trunk/tests/travis/setup/before_script.sh
  - ./trunk/tests/travis/setup/setup_apache.sh
  - ./trunk/tests/travis/setup/setup_selenium_server.sh

script:
  - phpunit --verbose --debug ./trunk/tests/travis/tests/
  - phpunit --verbose --debug ./trunk/tests/phpunit_selenium/tempTest.php

notifications:
  email:
    - d.asscheman@lumc.nl