## This is for LOVD3_development
language: php
php:
  # aliased to a recent 5.4.x version
  - 5.4
  # aliased to a recent 5.5.x version
#  - 5.5
  # aliased to a recent 5.6.xversion  
#  - 5.6
  # aliased to a recent 7.x version
#  - 7.0
#  - hhvm
#  - nightly

addons:
  firefox: "40.0"
  
sudo: required

before_install:
# for php 5.5
#  - curl -s -o $HOME/.phpenv/versions/5.5/bin/phpunit https://phar.phpunit.de/phpunit-old.phar
#  - chmod +x $HOME/.phpenv/versions/5.5/bin/phpunit
  - ./trunk/tests/travis/setup/setup_mysql.sh

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - ./trunk/tests/travis/setup/setup_apache.sh --githubaccount=dasscheman
  ## IMPORTANT! convert must be run AFTER the setup_apache.sh
  ## setup_apache.sh fix some assumptions where the files are stored!
  - ./trunk/tests/bash_scripts/convert_selenium_to_phpunit.sh --localhost=LOVD3_development --continueall
  - ./trunk/tests/travis/setup/setup_selenium_server.sh
  
script:
#  - ./vendor/bin/phpunit --verbose ./trunk/tests/phpunit_selenium/adminTest.php 
#  - phpunit ./trunk/tests/phpunit_selenium/adminTest.php
#  - phpunit ./trunk/tests/phpunit_selenium/authorizationTest.php
#  - phpunit ./trunk/tests/phpunit_selenium/collaboratorTest.php
#  - phpunit ./trunk/tests/phpunit_selenium/importTest.php
#  - phpunit ./trunk/tests/phpunit_selenium/managerTest.php
#  - phpunit ./trunk/tests/phpunit_selenium/submitterTest.php
#  - phpunit ./trunk/tests/phpunit_selenium/tempTest.php
  
## Run all tests
  - phpunit ./trunk/tests/phpunit_selenium/

#notifications:
#  email:
#    - d.asscheman@lumc.nl
